### ISSUE TITLE
Quick start error, console_show() wrong arguments

### ISSUE THREAD

**Issue by feiss** [tboox/xmake-sublime#1]
When trying to do a xmake/quick start, this message is shown in the console:
```
Traceback (most recent call last):
  File "/home/feiss/.config/sublime-text-3/Installed Packages/xmake.sublime-package/xmake.py", line 370, in __run_async
  File "/home/feiss/.config/sublime-text-3/Installed Packages/xmake.sublime-package/xmake.py", line 104, in get_projectdir
TypeError: console_show() takes 1 positional argument but 2 were given
```
###  Environment
* Linux lubuntu 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Sublime Text 3.2.1 Build 3207
* xmake v2.2.7+201907051049

**Comment by waruqi** [comment]
You need open a folder as project directory with *.c/*.cpp files first, then do xmake/quick start. It will generate a xmake.lua file in the opened folder.

1. create project directory with *.c/*.cpp files
2. use sublime to open this project directory
3. do xmake/quick start to generate xmake.lua 
4. do xmake/build to build project
5. do xmake/run to run target
